FROM tomcat:8.5.13-jre8


# update packages and install maven
RUN  \
  export DEBIAN_FRONTEND=noninteractive && \
  sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y openjdk-8-jdk && \
  apt-get install -y vim wget curl git maven

# attach volumes
VOLUME /volume/git

# create working directory
RUN mkdir -p /local/git
WORKDIR /local/git

# run terminal
# CMD ["/bin/bash"]

apt-get install 

# cd alexa-aem-demo
# mvn clean install
# scp target/alexa-aem-demo-1.0-SNAPSHOT.war <tomcat/webapps folder/askey.war># 

# RUN cd /opt/ey/nlp/ &&
#	mvn clean install &&
#  mv target/alexa-aem-demo-1.0-SNAPSHOT.war /usr/local/tomcat/webappsaskey.war


# NLP will send calls to:
# old: http://localhost:4503/content/ey/en/askey.html
# new: http://localhost:80/api/v1//alexa

# To change, modify src/main/java/com/ey/alexa/aem/AskEYSpeechlet.java

# To test, go to localhost:8080/askey/index.jsp

