nginx:
    image: nginx:1.10.3-alpine
    ports:
        - "80:80"
    links:
        - phpfpm
    volumes:
        # Internal code lives here
        - ./public:/var/www/html

        # Config
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

        # External codebase
        - ../alexa-d8/:/var/www/html/alexa-d8

        # Logs
        - ./logs/nginx-error.log:/var/log/nginx/error.log
        - ./logs/nginx-access.log:/var/log/nginx/access.log

phpfpm:
    container_name: phpfpm_extras
    build: .
    dockerfile: dockerfile-php

    ports:
        - "9000:9000"
    volumes:
        # Internal code lives here
        - ./public:/var/www/html

        # External codebase
        - ../alexa-d8/:/var/www/html/alexa-d8

        # Conf file lives here.
        - ./php/php-config.ini:/usr/local/etc/php/conf.d/php-config.ini

    links:
        - mysql

mysql:
  image: mariadb
  ports:
    - "3306:3006"
  environment:
    MYSQL_ROOT_PASSWORD: admin
    MYSQL_DATABASE: drupal
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal

  volumes:
    - ./mysql-data:/var/lib/mysql:rw
#    - ./mysql/conf.d:/etc/mysql/conf.d